### ISSUE TITLE
Vary background color

### ISSUE THREAD

**Issue by leapingllamas** [fchollet/ARC-AGI#10]
@fchollet An intelligent agent should be able to recognize focal objects versus background, even if background color might vary among training examples. 

There are various examples of deep-learned systems that recognize B&W digits well but fail spectacularly when colors are simply inverted. I would like to see an intelligent ARC-solver that is robust to this.

All the ARC examples I have seen so far have black backgrounds. Thus, I propose that ARC is augmented with examples with different background colors, sometimes yellow, sometimes white etc.

**Comment by jorijnsmit** [comment]
No! Don't make it even harder...!

Although there are some tasks included already that require you to detect shapes in colored 'noise'; e.g. `1c786137`.

**Comment by fchollet** [comment]
Sure, this is a good suggestion. We're not going to make changes like this to existing tasks, but we'll keep this in mind for future versions of the dataset.
