### ISSUE TITLE
05a7bcf2 has mistake in example output

### ISSUE THREAD

**Issue by mkl-nz** [fchollet/ARC-AGI#105]
![image](https://github.com/fchollet/ARC-AGI/assets/745165/e1e499bd-4e61-40da-8609-c26d6d1b1c99)

(annotated screenshot of https://arcprize.org/play?task=05a7bcf2)

The first example output seems to have a mistake in the rightmost vertical coloured strip.  I think the red block at x = 24, y = 27 (0-based) should be light blue.  In all the other coloured strips in example outputs, the groups of red blocks get pushed along the strip to the edge but don't change shape.  This group has gained an extra red block.

**Comment by CerebralAdvantage** [comment]
Also red block at x=25, y=28 should go from red to light blue.  Two squares.

**Comment by fchollet** [comment]
Thanks for the report.

> Also red block at x=25, y=28 should go from red to light blue. Two squares.

Can you illustrate what you mean with a picture?

**Comment by CerebralAdvantage** [comment]
![image](https://github.com/fchollet/ARC-AGI/assets/36646858/e4c97a0b-8d00-45fa-aee6-0a368567db15)

**Comment by fchollet** [comment]
Thanks. I've issued a fix.
