### ISSUE TITLE
Color-blind support

### ISSUE THREAD

**Issue by amahabal** [fchollet/ARC-AGI#107]
In the view, the grid is shown using color swatches. This is hard for me to parse. This can be easily remedied if the color number is additionally shown as text in each cell.

**Comment by amahabal** [comment]
All that is needed is this last line to the function shown in `common.js`. I did not send a pull request assuming you may want to do it optionally or something.

`function setCellSymbol(cell, symbol) {
    cell.attr('symbol', symbol);
    classesToRemove = ''
    for (i = 0; i < 10; i++) {
        classesToRemove += 'symbol_' + i + ' ';
    }
    cell.removeClass(classesToRemove);
    cell.addClass('symbol_' + symbol);
    cell.text(symbol);
}`

**Comment by fchollet** [comment]
> All that is needed is this last line to the function shown in common.js. I did not send a pull request assuming you may want to do it optionally or something.

We can do this, but let's gate it on a checkbox ("Show symbol numbers"). Please feel free to open a PR.

**Comment by neoneye** [comment]
There is rudimentary colorblindness support in ARC-Interactive. I'm not sure if it works well for all the colorblindness favors: deuteranopia, protanopia, tritanopia, others. Please let me know if you want it adjusted.

On the `Settings` page, change the `theme` to `Tol Muted`. 

https://neoneye.github.io/arc/settings.html?dataset=ARC&filter=entry

![Screenshot 2024-06-17 at 20 05 41](https://github.com/fchollet/ARC-AGI/assets/147971/26cc97cf-ba8e-4c6b-83c6-1cf02e389eba)

Afterwards goto `Tasks`

![Screenshot 2024-06-17 at 20 10 03](https://github.com/fchollet/ARC-AGI/assets/147971/472cc8bd-ed3e-49e8-b438-0a021847c36f)

**Comment by amahabal** [comment]
Thanks, @neoneye. That solution helps a bit to tell apart colors I cannot otherwise, but my bigger issue is that I also never automatically give names to colors (i.e., seeing a red patch does not evoke the word "red" in my mind or any other name), and that is needed for these tasks.

Just sent a pull request.

**Comment by fchollet** [comment]
Thanks for the PR, this is now merged.
