### ISSUE TITLE
ac0c5833 - 3rd training pair seems wrong

### ISSUE THREAD

**Issue by bananalemonmelon** [fchollet/ARC-AGI#112]
https://arcprize.org/play?task=ac0c5833

![image](https://github.com/fchollet/ARC-AGI/assets/576529/d17e6e68-2651-4ee2-a17b-99cf2c83967b)

In the 3rd pair (Ex. 3), the shape of the red-blocks in the input are different from the output.

**Comment by fchollet** [comment]
Indeed. This doesn't prevent solving the task, so we might treat as noise. But since this is a training pair, I think it's better to make the task as simple as possible and thus fix the inconsistency. I'll issue a fix.
