### ISSUE TITLE
In 3ee1011a - example 1 input, the green bar is one pixel too long

### ISSUE THREAD

**Issue by MischaMegens2** [fchollet/ARC-AGI#137]
In all the examples of this puzzle, the output consists of concentric squares constructed from the bars given in the input; the length of a bar matches the size of the corresponding square - except for the green bar in example 1. Also, the bars in each example are all of length even or all of length odd, so the resulting squares fit together nicely; except for the green bar, it does not fit. I'd venture it would make much more sense if the green bar had length 3, instead of 4.

**Comment by kungfu-eric** [comment]
Could be deliberate, a sort of noisy demonstration. You still got the right answer manually, right? Ain't that the point?

**Comment by MischaMegens2** [comment]
Oh I see, point taken. I'll just say it ain't pretty.
