### ISSUE TITLE
Version ARC

### ISSUE THREAD

**Issue by leapingllamas** [fchollet/ARC-AGI#27]
@fchollet as people are now coding against this, and as "we intend to keep adding new tasks to ARC in the future", can we please version/tag this repo, ideally with release notes listing ids of new or modified tasks.

**Comment by leapingllamas** [comment]
@fchollet now that this is a Kaggle competition, can we get some versioning on the dataset?

**Comment by fchollet** [comment]
The data for ARC-AGI 1 will stay unchanged apart from minor patches in case of inconsistency in a task. New tasks will be added as part of a new, separate version of the dataset, ARC-AGI 2.
