### ISSUE TITLE
Solution to task ef135b50.json

### ISSUE THREAD

**Issue by tomekster** [fchollet/ARC-AGI#28]
Could you please explain what is the rule used to generate output in the following task https://github.com/fchollet/ARC/blob/master/data/training/ef135b50.json ?

Demonstrations 1 and 2 suggest "Paint all black fields lying between two red fields dark red", but then demonstration 3 would look differently and solution to the actual task would look differently as well.

**Comment by weightwatchers-carlanderson** [comment]
![Screen_Shot_2020-01-20_at_7_15_45_PM](https://user-images.githubusercontent.com/39501603/72765266-900d4a00-3bb9-11ea-8263-8f7f366f5c4b.png)
I would agree. I think it is missing a dark red square

**Comment by petkovacs19** [comment]
It has been fixed with the above pr
