### ISSUE TITLE
2dee498d train 0 input breaks the pattern

### ISSUE THREAD

**Issue by leapingllamas** [fchollet/ARC-AGI#30]
it seems to me that 2dee498d train 0 input is inconsistent with the other inputs of this task.

train 1, train 2, and test 0 consist of a simple 1x3 tiling of the output. The central block of 1x3 tiling of train 0 is reversed, thus breaking the pattern across the inputs.

![issue](https://user-images.githubusercontent.com/1386343/74080390-9f8def00-4a11-11ea-94ad-80fb467c91f6.png)

**Comment by jmmcd** [comment]
Sorry for being a slowpoke/off-topic -- could you please share the tool you used to make this tables?

**Comment by weightwatchers-carlanderson** [comment]
@jmmcd sure, it is in this rejected PR: https://github.com/fchollet/ARC/pull/12
although I have made a few improvement to the CSS since

**Comment by jorijnsmit** [comment]
Agree. You could however also argue that the task is merely to extract the left-most or right-most 'block'.

**Comment by Blimpyway** [comment]
I'd say this is an exceptionally realistic pattern. Real world patterns are seldom perfectly matched.

**Comment by fchollet** [comment]
This is WAI.
