### ISSUE TITLE
Recursion Error After Certain Sequence of Operations

### ISSUE THREAD

**Issue by yutarochan** [fchollet/ARC-AGI#38]
While porting the ARC testing framework to an OpenAI Gym environment, my random operation testing revealed an issue with the Fill Operation. Given a certain combination of operations, the environment runs into a recursion error. 

This has been validated in both my Python implementation and the JS web interface of ARC testing (which was ported straight from the JS environment).

The commands on each line correspond to either fill or edit, followed by the row and col (indexed by 0) and the color symbol selections from the bottom pallete (also indexed by 0). 
```
EDIT 0 2 1
EDIT 0 2 2
FILL 0 1 5
EDIT 2 1 5
EDIT 0 1 6
FILL 2 1 3
FILL 2 1 4
FILL 2 1 2
EDIT 0 2 3
FILL 0 0 6
EDIT 0 0 3
FILL 0 1 5
EDIT 2 0 3
> maximum recursion depth exceeded in comparison
```

**Comment by gkamradt** [comment]
I'm unable to repro this issue

Can you confirm it is still an error? Quite a bit of time has elapsed
