### ISSUE TITLE
Adding customised tasks ?

### ISSUE THREAD

**Issue by christophelebrun** [fchollet/ARC-AGI#46]
In the app, would it be possible to let us create our own tasks ?
I guess such a tool was used to create the tasks, could it be possible to share it ?

**Comment by neoneye** [comment]
For tweaking pixels of an existing task, I have good experience using Victor Vikram Odouard's editor 
https://github.com/victorvikram/arc-site

**Comment by fchollet** [comment]
That's a good suggestion. I was originally planning on making a task editor public, but other people have released their own editors since.
