### ISSUE TITLE
Train Task a9f96cdd.json - Problem with One Point

### ISSUE THREAD

**Issue by huntergregory** [fchollet/ARC-AGI#51]
The fourth training output includes the red point from the input. From the other 3 training/output pairs and the test input/output pair, it seems the task is to add the 4 colored points centered around the red point and then remove the red point (make it black).

![image](https://user-images.githubusercontent.com/42728408/77245665-a86c0600-6bf6-11ea-8198-6bf21bc0ba00.png)

**Comment by petkovacs19** [comment]
It has been fixed with the above pr
