### ISSUE TITLE
20818e16 and b0f4d537 has mistype 

### ISSUE THREAD

**Issue by qent** [fchollet/ARC-AGI#63]
my model told me that:
evaluation/20818e16.json ['train'][2]['output'] - size(9,8) => (8,8)
evaluation/b0f4d537.json ['train'][0]['output'] - middle line need move 1px righter
seems its true =)

**Comment by neoneye** [comment]
I can confirm that `b0f4d537` has been fixed.
[ARC-Interactive with the fixed task](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=b0f4d537_v2)
![b0f4d537_v2](https://github.com/fchollet/ARC/assets/147971/6128d389-06f4-4b57-8d35-db62e1c80aaf)

However `20818e16` has not been fixed, so this issue cannot be closed yet.

**Comment by fchollet** [comment]
Issuing a fix.

**Comment by neoneye** [comment]
I can confirm the fixes works. Thank you.

[task 20818e16](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=20818e16_v2) and [task b0f4d537](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=b0f4d537_v2)
