### ISSUE TITLE
bd14c3bf test input top left object should be red

### ISSUE THREAD

**Issue by VilmosProkaj** [fchollet/ARC-AGI#73]
task bd14c3bf from the evaluation dataset picks one object with color red and all similar objects are colored to red in the output. However on the test input image all objects are blue.

![Screenshot from 2020-05-25 20-24-27](https://user-images.githubusercontent.com/14357713/82835982-de16bf00-9ec5-11ea-9442-cf3221f2f686.png)

**Comment by neoneye** [comment]
As of 2024-may-22 this is still an issue.

[ARC-Interactive](https://neoneye.github.io/arc-staging/edit.html?dataset=ARC&task=bd14c3bf)
![bd14c3bf](https://github.com/fchollet/ARC/assets/147971/5dac1ce0-a76e-47fc-b03a-91fef029b11e)

I have made a fix for it, [bd14c3bf_v2.json](https://github.com/neoneye/arc-dataset-collection/blob/main/dataset/ARC/data/evaluation/bd14c3bf_v2.json)
[ARC-Interactive with fixed file](https://neoneye.github.io/arc-staging/edit.html?dataset=ARC&task=bd14c3bf_v2)

**Comment by neoneye** [comment]
This issue can be closed now.
