### ISSUE TITLE
9def23fe train[0] output

### ISSUE THREAD

**Issue by VilmosProkaj** [fchollet/ARC-AGI#74]
There are two extra red pixel in the first train output. As I understand in this task the red square emits horizontal and vertical rays unless there is a non-red and non-black pixel that prevents it.
![Screenshot from 2020-05-26 06-33-38](https://user-images.githubusercontent.com/14357713/82860771-f95fe980-9f1a-11ea-8c2f-dbf1e632d737.png)

**Comment by neoneye** [comment]
Highlighted with white circle. IMHO this is a minor issue.

[ARC-Interactive](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=9def23fe)
![Screenshot 2024-04-24 at 14 50 02](https://github.com/fchollet/ARC/assets/147971/a6285cf3-c7a3-4c85-8c35-5cbe080fab9a)

**Comment by fchollet** [comment]
Issuing a fix.

**Comment by neoneye** [comment]
I can confirm your fix works.

[task 9def23fe](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=9def23fe_v2)
