### ISSUE TITLE
9edfc990 incorrect pixel in second output

### ISSUE THREAD

**Issue by roks** [fchollet/ARC-AGI#77]
pixel (13, 6) should be blue

![Screen Shot 2020-09-23 at 12 23 34 AM](https://user-images.githubusercontent.com/1727553/93981352-b8df7380-fd34-11ea-9bbd-170a5365c08c.png)

**Comment by neoneye** [comment]
See the red circle. This is one of the training pairs.

[ARC-Interactive](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=9edfc990)

![Screenshot 2024-04-24 at 14 39 49](https://github.com/fchollet/ARC/assets/147971/794147d9-ba3a-4265-bf71-cee226e0fc00)

**Comment by fchollet** [comment]
Pretty minor indeed. Issuing a fix for this anyway.

**Comment by neoneye** [comment]
I can confirm that your fix works.

[task 9edfc990](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=9edfc990_v2)
