### ISSUE TITLE
Add Kaggle Competition Link to README.md

### ISSUE THREAD

**Issue by JamesMcGuigan** [fchollet/ARC-AGI#78]
The Kaggle Competition to solve this dataset has now finished but contains a wealth of knowledge regarding different approaches for trying to solve it. It is probably worth including a link in the README.md.
- https://www.kaggle.com/c/abstraction-and-reasoning-challenge

**Comment by gkamradt** [comment]
Yes +1 to this! But for the updated competition at ARCprize.org

**Comment by fchollet** [comment]
Done!
