### ISSUE TITLE
8FBCA751.json seems to have two correct solutions

### ISSUE THREAD

**Issue by volotat** [fchollet/ARC-AGI#84]
![image](https://user-images.githubusercontent.com/14307880/128630920-c90f14bb-04a5-416a-88b9-42d5d6122033.png)
The following image is an intended solution for the task. It assumes that bottom and top blocks fully connected between themselves. But if we don't assume that, following solution also seems feasible.
![image](https://user-images.githubusercontent.com/14307880/128630972-f997becc-4298-4e62-a52a-fbaef4c70800.png)

**Comment by fchollet** [comment]
This is an acceptable level of ambiguity -- the two possible solutions can be tested by using 2 attempts.
