### ISSUE TITLE
B7CB93AC.json is not unambiguous

### ISSUE THREAD

**Issue by volotat** [fchollet/ARC-AGI#88]
Not exactly an issue, but most of the task in the dataset seems to have single unambiguous solutions while this and couple of others doesn't.

![image](https://user-images.githubusercontent.com/14307880/130367439-9f4587d9-4d7e-4b54-9f00-131a4f429805.png)
According to the rule we have to combine shapes in a way such that we get complete rectangle. Rotation is allowed. With that in mind solution like this should also be correct.
![image](https://user-images.githubusercontent.com/14307880/130367523-949f152b-34b1-42db-bf46-a64b1230b636.png)

**Comment by fchollet** [comment]
This is an acceptable level of ambiguity -- as long as there are no more than 2 likely solutions, we're clear. This is the reason why you're allowed several attempts per test grid.
