### ISSUE TITLE
4852f2fa train output - move one pixel

### ISSUE THREAD

**Issue by neoneye** [fchollet/ARC-AGI#94]
[ARC-Interactive](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=4852f2fa)

This issue is also reported here: https://github.com/volotat/ARC-Game/issues/4

The output repeats the shape. But the repeat is inconsistent in the first training pair. 

The light blue pixel in the bottom of the light blue shape, is misplaced by 1 pixel.
![4852f2fa](https://github.com/fchollet/ARC/assets/147971/9d9cb3e3-1bf4-420e-8912-0b7710bcb842)

This task has many training pairs to learn from, so no worries. The real world is rarely perfect.

**Comment by fchollet** [comment]
Thanks for the reports. I issued a fix for this task (live at HEAD).
