### ISSUE TITLE
c35c1b4c train output 3 is asymmetric

### ISSUE THREAD

**Issue by neoneye** [fchollet/ARC-AGI#96]
[ARC-Interactive](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=c35c1b4c)

The shape has to be horizontal symmetric.

However in train output 3, it's asymmetric due to a single pixel.

![c35c1b4c_wrong](https://github.com/fchollet/ARC/assets/147971/9d540ac9-21e4-4b3f-a857-6f5f91a8c844)

Credit to user `a` on lab42 Discord for reporting this.

**Comment by fchollet** [comment]
Thanks for the reports. I issued a fix for this task (live at HEAD).
