### ISSUE TITLE
b230c067 make less ambiguous, so it doesn't require 2 attempts

### ISSUE THREAD

**Issue by neoneye** [fchollet/ARC-AGI#97]
# Problem

[ARC-Interactive](https://neoneye.github.io/arc/edit.html?dataset=ARC&task=b230c067)

I used 2 attempts at solving this task. By making it more explicit, I think it can be reduced to 1 attempt.
![Screenshot 2024-02-03 at 11 57 48](https://github.com/fchollet/ARC/assets/147971/5741e4f9-35ca-4b60-98c2-e9da4a746489)

## Attempt 1 - incorrect
At first glance, it seems the top-right object should be colored `red`, like this. But it's incorrect.
![Screenshot 2024-02-03 at 12 20 23](https://github.com/fchollet/ARC/assets/147971/8773b758-5ac5-446c-838e-417f908cd53b)

## Attempt 2 - correct
My second take. Objects with the identical shape gets colored `blue`, and odd-shapes colored `red`. This is correct.
![Screenshot 2024-02-03 at 12 19 58](https://github.com/fchollet/ARC/assets/147971/75cae5db-b1ef-4372-a5dc-349f2f816765)

# Solution

To make it less-ambiguous, I suggest rotating by 180 degrees on the first training pair, so it looks like this. This rules out the failed attempt 1.
![b230c067-proposed-solution2](https://github.com/fchollet/ARC/assets/147971/558b6cf1-e96c-4666-983a-231e42de5c3c)

**Comment by fchollet** [comment]
Thanks for the reports. I issued a fix for this task (live at HEAD). The fix is to add a demonstration task.
